# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run release
    - name: Copy index.html
      uses: canastro/copy-action@0.0.2
      with:
        source: index.html
        target: dist/index.html
    - name: Copy favicon.png
      uses: canastro/copy-action@0.0.2
      with:
        source: favicon.png
        target: dist/favicon.png
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.2.1
      with:
        email: thibault.david@gmail.com
        build_dir: dist
        branch: gh-pages
        cname: homepage.leddt.com
